# Generated by Django 3.1.6 on 2021-04-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_stripeuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeuser',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
