# Generated by Django 3.1.6 on 2021-04-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_stripeuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trackingNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
